name: Playwright Tests
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      # run any `bun` or `bunx` command
      - name: Installing bun dependencies
        run: bun install && bun install --frozen-lockfile && bun run build
      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps || bunx playwright install --with-deps
      - name: Run Playwright tests
        run: bun run test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
